name: &name 'Experiment name'

# Base directory for notebooks  (relative or absolute link).
base_dir: "example_notebooks"
# target_dir: "C:\\Experiments\\Experiment_name"

# Target website output directory (relative or absolute link).
html_target_dir: "docs"
# Once connected to the group NAS, should be set to the following:
#html_target_dir: "\\\\FQT_NAS\\web"

# Target directory for PDF output (relative or absolute link)
pdf_target_dir: "pdf_output"

# Main sections of website
sections:
  # Each section has a title (e.g. General Information)
  "General information":
    # The title should contain the relative path w.r.t.base_dir.
    # The path can either lead to a notebook, or to a folder containing notebooks
    path: "General information.ipynb"
    # The notebook_class specifies how the converter should process the notebook
    # The default class is simply 'Notebook', but can be different (see below)
    notebook_class: "Notebook"

  # Here we specify that the notebooks in this folder are LogNotebooks, i.e.
  # they are used for logging. This will have consequences during conversion,
  # in particular it will allow the converter to extract useful information.
  "Analysis":
    path: "Analysis"
    notebook_class: "LogNotebook"

# Template settings for generating a website from notebooks.
template:
  footer: "&copy 2015-2018 Names of experimenters at Andrea Morello's lab, UNSW"

# Settings after here are advanced and should generally not be touched.
  template_dir: "templates"  # Directory for templates
  # Depth of website, by default 1. Should be increased if this website is not
  # at the main level (e.g. not a main project)
  site_depth: 1
  version: '1.0'
  experiment_title: *name
  theme: 'cosmo'   # Julia theme to use
  jt_theme_link: ''
  auto_highlight_1: 'null'  # Not relevant
  auto_highlight_0: 'pack'  # Not relevant
  font: "Droid Sans"
  sidebar:  # Settings for the sidebar (containing TOC)
    enabled: True
    logo_source: '' # Source for logo image (not added if empty)
    homepage: ''
  toc:  # Settings for the table of contents
    threshold: 3 # Max header level to display
    number_sections: 0 # Whether to number the sections

  # These items are set while generating templates
  navbar_sections: {}
  base_path: None  # relative path to base
  site_libs_path: None  # relative path to site libs
  parents: None  # {parent_name: relative parent link}
  notebook_name: None  # Name of current notebook