name: 'Experiment name'

# Base directory for notebooks  (relative or absolute link).
base_dir: "example_notebooks"
# target_dir: "C:\\Experiments\\Experiment_name"

# Target website output directory (relative or absolute link).
html_target_dir: "docs"

# Target directory for PDF output (relative or absolute link)
pdf_target_dir: "pdf_output"

# Main sections of website
sections:
  # Each section has a title (e.g. General Information)
  # If the value is a single string, this is the relative path w.r.t. base-dir.
  # The path can either lead to a notebook, or to a folder containing notebooks
  "General information": "General information.ipynb"

  # Instead of a string, the value can also be key-value pairs to provide
  # additional information about the notebook folder.
  # In this case, we not only specify the relative path, but also that the
  # notebooks in this folder are LogNotebooks (used for logging), and so
  # during the conversion, they are treated as such.
  "Analysis":
    path: "Analysis"
    notebook_class: "LogNotebook"

# Template settings for generating a website from notebooks.
template:
  template_dir: "templates"  # Directory for templates
  footer: "&copy 2015-2018 Names of experimenters at Andrea Morello's lab, UNSW"
  experiment_title: 'My experiment'

  # Settings after here are advanced and should generally not be touched.
  version: '1.0'
  theme: 'cosmo'   # Julia theme to use
  jt_theme_link: ''
  auto_highlight_1: 'null'  # Not relevant
  auto_highlight_0: 'pack'  # Not relevant
  font: "Droid Sans"
  sidebar:  # Settings for the sidebar (containing TOC)
    enabled: True
    logo_source: '' # Source for logo image (not added if empty)
    homepage: ''
  toc:  # Settings for the table of contents
    threshold: 3 # Max header level to display
    number_sections: 0 # Whether to number the sections

  # These items are set while generating templates
  navbar_sections: {}
  base_path: None  # relative path to base
  site_libs_path: None  # relative path to site libs
  parents: None  # {parent_name: relative parent link}
  notebook_name: None  # Name of current notebook